AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation template to create an S3 bucket and an EC2 instance"

Metadata:
  Author: "vipun sanjna"
  Version: "1.1"
  Purpose: "Create an S3 bucket with versioning and a basic EC2 instance"

Parameters:
  BucketName:
    Type: String
    Description: "The name of the S3 bucket to create"
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "^[a-z0-9.-]+$"
    ConstraintDescription: "Bucket name must be lowercase letters, numbers, periods, or hyphens."

Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: "Enabled"

  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-0c02fb55956c7d316  
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: "MyEC2Instance"

Outputs:
  BucketName:
    Description: "The name of the created S3 bucket"
    Value: !Ref BucketName

  BucketArn:
    Description: "The ARN of the created S3 bucket"
    Value: !GetAtt MyS3Bucket.Arn

  BucketDomainName:
    Description: "The domain name of the created S3 bucket"
    Value: !GetAtt MyS3Bucket.DomainName

  EC2InstanceId:
    Description: "The ID of the created EC2 instance"
    Value: !Ref MyEC2Instance
